server:
  port: 32019


spring:
  application:
    name: top-admin-boot
  cloud:
    nacos:
      discovery:
        server-addr: nacos-server:8848
        group: top-cloud


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always