apiVersion: apps/v1
kind: Deployment
metadata:
  name: top-member
spec:
  replicas: 1
  selector:
    matchLabels:
      app: top-member
  template:
    metadata:
      labels:
        app: top-member
    spec:
      imagePullSecrets:
        - name: top-cloud
      tolerations:
        - effect: NoExecute
          key: project
          operator: Equal
          value: top-cloud
      serviceAccount: {{ .Values.service_account }}
      serviceAccountName: {{ .Values.service_account }}
      containers:
        - image: {{ .Values.top_member_service_image }}:{{ .Values.top_version }}
          imagePullPolicy: Always
          name: top-member
          resources:
            limits:
              cpu: "0.3"
              memory: 0.8Gi
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: top-config
                  key: MYSQL_DATABASE_URL
            - name: SPRING_DATASOURCE_DRIVER-CLASS-NAME
              valueFrom:
                configMapKeyRef:
                  name: top-config
                  key: DRIVER_CLASS_NAME
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: top-config
                  key: MYSQL_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: top-config
                  key: MYSQL_PASSWORD
            - name: SPRING_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: top-config
                  key: REDIS_HOST
            - name: SPRING_REDIS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: top-config
                  key: REDIS_PASSWORD
            - name: SPRING_REDIS_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: top-config
                  key: REDIS_DATABASE
---
apiVersion: v1
kind: Service
metadata:
  name: top-member
  labels:
    app: top-member
spec:
  type: ClusterIP
  ports:
    - port: 32018
  selector:
    app: top-member
