apiVersion: apps/v1
kind: Deployment
metadata:
  name: top-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: top-gateway
  template:
    metadata:
      labels:
        app: top-gateway
    spec:
      imagePullSecrets:
        - name: top-cloud
      tolerations:
        - effect: NoExecute
          key: project
          operator: Equal
          value: top-cloud
      serviceAccount: {{ .Values.service_account }}
      serviceAccountName: {{ .Values.service_account }}
      containers:
        - image: {{ .Values.top_gateway_image }}:{{ .Values.top_version }}
          imagePullPolicy: Always
          name: top-gateway
          resources:
            limits:
              cpu: "1"
              memory: 1.5Gi
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: top-config
                  key: MYSQL_DATABASE_URL
            - name: SPRING_DATASOURCE_DRIVER-CLASS-NAME
              valueFrom:
                configMapKeyRef:
                  name: top-config
                  key: DRIVER_CLASS_NAME
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: top-config
                  key: MYSQL_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: top-config
                  key: MYSQL_PASSWORD
            - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: top-config
                  key: KAFKA_SERVER
            - name: SPRING_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: top-config
                  key: REDIS_HOST
            - name: SPRING_REDIS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: top-config
                  key: REDIS_PASSWORD
            - name: SPRING_REDIS_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: top-config
                  key: REDIS_DATABASE
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: top-config
                  key: PROFILES_ACTIVE
---
apiVersion: v1
kind: Service
metadata:
  name: top-gateway
  labels:
    app: top-gateway
spec:
  type: ClusterIP
  ports:
    - port: 32015

  selector:
    app: top-gateway
