spring:
  application:
    name: top-member

server:
  port: 32018

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

swagger2:
  basePackage: com.ihave.controller
  name: top-member
  url: https://www.ihave.top
  email: jchen_px@126.com
  title: top-cloud
  description: top-cloud
  version: V1.0.0


feign:
  httpclient:
    connection-timeout: 8000
